Fixes Advisory: CVE-2020-26247
sul-dlss/mylibrary pull request #628
Opened 2021-01-04 21:42 UTC by jgreben

2021-01-04 21:59 UTC, mejackreed requested changes
Overall looks good to me, just one minor comment.

2021-01-04 21:59 UTC, mejackreed commented on Gemfile
> +# Fixes Advisory: CVE-2020-26247
Can we get away with just doing a `bundle update` with commenting about the CVE or specifying a version? I mention this just as it might become troublesome to try and keep track of that.

2021-01-04 22:50 UTC, jgreben commented on Gemfile
> +# Fixes Advisory: CVE-2020-26247
Ok, I updated the Gemfile.lock and removed the version pinning and changed the Gemfile comment.

2021-01-04 23:38 UTC, mejackreed commented on Gemfile
> +# Fixes Advisory: CVE-2020-26247
Great! Looks like there is a Rubocop issue still. I would be fine if you wanted to remove the comment entirely.

2021-01-05 00:01 UTC, mejackreed approved these changes
👏

2021-01-05 00:01 UTC, merged