Update layout of feedback form (#571)
sul-dlss/mylibrary pull request #704
Opened 2022-01-07 00:05 UTC by thatbudakguy

Borrows layout from SearchWorks, see:
https://github.com/sul-dlss/SearchWorks/pull/2660

2022-01-07 21:04 UTC, thatbudakguy commented
I've deployed this branch to UAT (https://mylibrary-uat.stanford.edu) so that you can see what the form looks like. I tried to match the image in https://github.com/sul-dlss/mylibrary/issues/571, but SearchWorks seems a bit different from that, so advice is appreciated.

2022-01-07 22:13 UTC, ggeisler requested changes
This looks great to me @thatbudakguy.

I haven only the most minor comment, which is that the "Check system status" text is in bold here, while we don't use bold for it in our other applications, I don't think. I don't really mind the bold, but then again, this link isn't the main point of the form and it wouldn't hurt to be consistent across apps, so maybe remove the bold styling?

2022-01-10 21:00 UTC, thatbudakguy commented
ok, unbolded the text and redeployed to UAT. not sure if we need another review since it's (theoretically) just frontend code changing, but i'll leave it up for awhile in case anyone else wants to review

2022-01-11 19:33 UTC, camillevilla approved these changes

2022-01-11 19:34 UTC, merged